/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.higorpalmeira.github.gerenciadorconsultas.view;

/**
 *
 * @author higor
 */
public class frmPrincipal extends frmGenerico {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JMenuBar();
        mitConsultas = new javax.swing.JMenu();
        mitPacientes = new javax.swing.JMenu();
        mitMedicos = new javax.swing.JMenu();
        mitEspecialidades = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGC - Sistema de Gerenciamento de Consultas");
        setResizable(false);

        menuPrincipal.setPreferredSize(new java.awt.Dimension(265, 40));

        mitConsultas.setText("Consultas");
        mitConsultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPrincipal.add(mitConsultas);

        mitPacientes.setText("Pacientes");
        mitPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPrincipal.add(mitPacientes);

        mitMedicos.setText("Médicos");
        mitMedicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mitMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mitMedicosMouseClicked(evt);
            }
        });
        menuPrincipal.add(mitMedicos);

        mitEspecialidades.setText("Especialidades");
        mitEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mitEspecialidades.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mitEspecialidadesMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mitEspecialidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mitEspecialidadesMouseClicked(evt);
            }
        });
        mitEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEspecialidadesActionPerformed(evt);
            }
        });
        menuPrincipal.add(mitEspecialidades);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mitEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEspecialidadesActionPerformed
        
        
    }//GEN-LAST:event_mitEspecialidadesActionPerformed

    private void mitEspecialidadesMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mitEspecialidadesMenuKeyPressed

    }//GEN-LAST:event_mitEspecialidadesMenuKeyPressed

    private void mitEspecialidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitEspecialidadesMouseClicked

        frmEspecialidade frmEspecialidade = new frmEspecialidade();
        frmEspecialidade.setVisible(true);

    }//GEN-LAST:event_mitEspecialidadesMouseClicked

    private void mitMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitMedicosMouseClicked

        frmMedico frmMedico = new frmMedico();
        frmMedico.setVisible(true);

    }//GEN-LAST:event_mitMedicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu mitConsultas;
    private javax.swing.JMenu mitEspecialidades;
    private javax.swing.JMenu mitMedicos;
    private javax.swing.JMenu mitPacientes;
    // End of variables declaration//GEN-END:variables
}
